### ISSUE TITLE
Integrate with Web Push plugin

### ISSUE THREAD

**Issue by delapuente** [mozilla/wp-add-to-homescreen#16]
To provide the complete add-to-homescreen experience, it is necessary to provide a web manifest (and probably a sw) but Web Push is already providing one so both plugins should collaborate seamlessly.

**Comment by marco-c** [comment]
I've already done this with https://github.com/mozilla/wp-app-manifest/pull/2.

**Comment by delapuente** [comment]
Let's keep it open as there is no plugin yet so it makes no sense to talk about an nonexistent implementation.

**Comment by marco-c** [comment]
Yes, although if we keep using the class introduced with https://github.com/mozilla/wp-app-manifest/pull/2, compatibility should come for free.
We just need to validate that they are indeed compatible, once this plugins adds more fields to the manifest.

**Comment by delapuente** [comment]
Yes, sure. That [continues being there](https://github.com/mozilla/wp-add-to-homescreen/blob/master/wp-add-to-homescreen/composer.json) and I have the code in the PR and in the Web Push plugin to refer to.
