### ISSUE TITLE
localForage path error causes plugin to not work

### ISSUE THREAD

**Issue by darkwing** [mozilla/wp-add-to-homescreen#50]
I saw this error occurring today:

<img width="1662" alt="error" src="https://cloud.githubusercontent.com/assets/46655/14163657/2c86c762-f6bd-11e5-8e1a-23d729fbff06.png">

The problem is that "localForage" needs to be "localforage"

**Comment by delapuente** [comment]
Yes, it's something I noticed when visiting your blog. How did you install the plugin?

**Comment by delapuente** [comment]
Some should have warn me about the Mac filesystem being case unsensitive!

**Comment by delapuente** [comment]
Version 0.2.0 has been released. Please, update the plugin and the problem should be gone.
